// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngieqrldgaumlivdzsur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5naWVxcmxkZ2F1bWxpdmR6c3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMDMxMzgsImV4cCI6MjA3Nzg3OTEzOH0.mFGuU2uJyFu49k_X0_CDK3OKIzpQ7xdVs7sAOP0fNic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});